#!/usr/bin/env python
"""
This node is called flip. It publishes velocity commands in the form of Twist messages to the /diff/cmd_vel topic.

"""
import rospy
import tf2_ros
import geometry_msgs.msg
from sensor_msgs.msg import JointState


class MoveToPoint:
    def __init__(self):
        self.pub = rospy.Publisher('/joint_state_publisher', JointState, queue_size=5)
        self.joint_states()
        rospy.Timer()


    def joint_states(self):
        mtp = JointState()
        mtp.name = ['panda_joint1','panda_joint2','panda_joint3','panda_joint4','panda_joint5','panda_joint6','panda_joint7']
        mtp.position = [0.10022933204039225, -0.38842216264896545, -0.1033460415343626, -2.5514113638655007, -0.05330979986187987, 2.173777705245548, 1]



if __name__ == "__main__":
    rospy.init_node("bamboo")
    node = MoveToPoint()