#!/usr/bin/env python3
'''
use control theta to control xddot, to get the desired velocity (both in acceleration zone constant zone and deceleration zone)

PUBLISHERS:
  + 
SUBSCRIBERS
  +  
SERVICES:
  none
PARAMETERS
  + none
'''
#imports
import rospy
from balance_board.msg import BoardPose,Ball_pose, PlotPoint
from balance_board.srv import Gains
from board_pid import BoardPid
import numpy as np
# import geometry_msgs.msg

class PD:
    def __init__(self):
        '''
        The initiation function of the flip. Initiates subscribers and variables
        INPUTS:
            none
        OUTPUTS:
            none
        '''
 
        self.t = np.arange(0, 250)
        self.x = 375+100*np.cos((2*np.pi/250) * self.t)
        self.y = 300+100*np.sin((2*np.pi/250) * self.t)

        
        # inits publishers, subscribers services
        self.targ_pub = rospy.Publisher('target', Ball_pose, queue_size=10)
        self.timer = rospy.Timer(rospy.Duration(secs=(1/50)), self.timer_callback)

        self.i = 0

    def timer_callback(self, msg):
        print("yay")
        new_pose = Ball_pose()
        new_pose.x_way = self.x[self.i]
        new_pose.y_way = self.y[self.i]

        self.targ_pub.publish(new_pose)
        self.i = self.i + 1

        if self.i == 250:
            self.i = 0

def main():
    
    rospy.init_node('nested_pd_controller', anonymous=True)
    controller = PD()
    rospy.spin()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass