#!/usr/bin/env python3

import rospy
from std_srvs.srv import Empty, EmptyResponse
from balance_board.msg import PlotPoint
from plotter import Plotter

class PlotNode:
     
    def __init__(self):
      self.plotter = Plotter()

      self.log = rospy.Subscriber("plot_log", PlotPoint, self.log_callback)
      self.plot = rospy.Service("plot", Empty, self.plot_callback)
      self.reset = rospy.Service("reset", Empty, self.reset_callback)

    def log_callback(self, msg):
      self.plotter.log(msg.plot, msg.line, msg.value)

    def plot_callback(self, msg):
      self.plotter.plot()
      return EmptyResponse()

    def reset_callback(self, msg):
      self.plotter.reset()
      return EmptyResponse()



rospy.init_node('plot_node')
myPlotNode = PlotNode()
rospy.spin()
