balanciaga:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_position_controller:
    type: position_controllers/JointPositionController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

    joint: panda_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
    joint: panda_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
    joint: panda_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}
    joint: panda_joint4
    pid: {p: 100.0, i: 0.01, d: 10.0}
    joint: panda_joint5
    pid: {p: 100.0, i: 0.01, d: 10.0}
    joint: panda_joint6
    pid: {p: 100.0, i: 0.01, d: 10.0}
    joint: panda_joint7
    pid: {p: 100.0, i: 0.01, d: 10.0}

